# -*- coding: utf-8 -*-
"""cyp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HAkKK3jDiR4mSZxeF7RuQyNvpARwf7_Y
"""

import pandas as pd

def cyp_concat(train, test, args.train_path, args.test_path):

    # Load dataframes from paths
    swiss1 = pd.read_csv(train_path)
    swiss2 = pd.read_csv(test_path)

    # Concatenate dataframes
    concat_df1 = pd.concat([train, swiss1], ignore_index=True)
    concat_df2 = pd.concat([test, swiss2], ignore_index=True)

    return concat_df1, concat_df2