# -*- coding: utf-8 -*-
"""similarity_features.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nLqU_3dZ8mxMg_9zK1iWBTklafbmDOjz
"""

import pandas as pd
from rdkit import Chem
from rdkit import DataStructs
from rdkit.Chem import AllChem

def compute_similarity(smiles1, smiles2, nBits=1024):
    mol1 = Chem.MolFromSmiles(smiles1)
    mol2 = Chem.MolFromSmiles(smiles2)

    fp1 = AllChem.GetMorganFingerprintAsBitVect(mol1, 2, nBits=nBits)
    fp2 = AllChem.GetMorganFingerprintAsBitVect(mol2, 2, nBits=nBits)

    return DataStructs.TanimotoSimilarity(fp1, fp2)

def add_similarity_features(df, nBits):
    mlm_max = df.iloc[662,1] if len(df) > 662 else None
    mlm_min = df.iloc[23,1] if len(df) > 23 else None
    hlm_max = df.iloc[1584,1] if len(df) > 1584 else None
    hlm_min = df.iloc[23,1] if len(df) > 23 else None
    maxgap = df.iloc[1584,1] if len(df) > 1584 else None
    mingap = df.iloc[22,1] if len(df) > 22 else None

    standards = [mlm_max, mlm_min, hlm_max, hlm_min, maxgap, mingap]
    standard_names = ['mlm_max', 'mlm_min', 'hlm_max', 'hlm_min', 'maxgap', 'mingap']

    results = []
    for smiles in df['SMILES']:
        similarities = [compute_similarity(smiles, standard, nBits) for standard in standards]
        results.append(similarities)

    df_similarities = pd.DataFrame(results, columns=standard_names)

    return pd.concat([df, df_similarities], axis=1)