# -*- coding: utf-8 -*-
"""Zagreb_index.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yJuBFwohkQdYOihXpqLliBHD6GKewug8
"""

from rdkit import Chem
from rdkit.Chem import Descriptors

def calculate_zagreb_index(df, smiles_column='SMILES'):

    def get_zagreb(smiles):
        """Helper function to get the Zagreb index for a SMILES string."""
        mol = Chem.MolFromSmiles(smiles)
        if mol:  # Check if the molecule was correctly created
            return Descriptors.BalabanJ(mol)
        else:
            return None  # Return None for invalid SMILES

    # Apply the helper function to the specified SMILES column
    df['zagreb_index'] = df[smiles_column].apply(get_zagreb)

    return df